
FROM python:3.10

# 设置工作目录
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# 设置启动命令（启动 FastAPI 应用）
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]